### PR TITLE
Add "silent" option to Repeat rule

### PR DESCRIPTION
**Pull request by gchauvet**
Dear Vertx dev's

I propose a new option to the "Repeat" feature, to avoid iteration messages in the console.

Best regards,

### CODE REVIEW

**Comment by vietj** [comment]
Hi,

did you sign the Eclipse CLA ?

**Comment by gchauvet** [comment]
Oops, I forget this part; I do this ASAP

**Comment by gchauvet** [comment]
Done. I've noticed that commits must be pushed with -s option, but I didn't do that for this pull. Is it an issue ?

**Comment by vietj** [comment]
it's fine: it's not required for Vert.x Unit - only for Vert.x Core

**Comment by gchauvet** [comment]
When did you review my contrib ?
I've a new improvement to submit who depend of this pull request

**Comment by vietj** [comment]
hi it should have been included in 3.3.0 but has not been done

**Comment by vietj** [comment]
merged now

**Pull request merged**
