### PR TITLE
CLI "vertx test" not reporting failed tests to exit status code

### PR DESCRIPTION
**Pull request by imavroukakis**
inspect the completion status and exit with the appropriate code

### CODE REVIEW

**Comment by vietj** [comment]
could you also update the documentation about the return status code ? i.e 0 == ok > 0 means the number of failures

**Comment by imavroukakis** [comment]
Sure, on it.

**Comment by imavroukakis** [comment]
squashed and pushed.

**Comment by vietj** [comment]
last point, have you signed the Eclipse CLA ? see https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

**Comment by imavroukakis** [comment]
Yup :)

**Comment by vietj** [comment]
awesome thanks

**Pull request merged**
